### ISSUE TITLE
S3 remote with SSO configuration failing to get SSO Token

### ISSUE THREAD

**Issue by d-walkama** [iterative/dvc-s3#36] opened 2023-03-13 15:49 UTC
Hello,

I've recently began using AWS with SSO and have been successful in using `aws sso login`, but cannot seem to get dvc to cooperate, below is the error I receive when I run `dvc push` with a S3 remote as default (this is the tail of the error, the full error is just a repetition of this several hundred times):  

```
Traceback (most recent call last):
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/botocore/utils.py", line 2773, in __call__
    token = self._cache[cache_key]
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/botocore/credentials.py", line 325, in __getitem__
    raise KeyError(cache_key)
KeyError: 'a7b00e6f99586adf164f6d395b1e7d4a2e3a8baf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/aiobotocore/credentials.py", line 321, in _protected_refresh
    metadata = await self._refresh_using()
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/aiobotocore/credentials.py", line 379, in fetch_credentials
    return await self._get_cached_credentials()
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/aiobotocore/credentials.py", line 389, in _get_cached_credentials
    response = await self._get_credentials()
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/aiobotocore/credentials.py", line 1013, in _get_credentials
    'accessToken': self._token_loader(self._start_url),
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/botocore/utils.py", line 2781, in __call__
    raise SSOTokenLoadError(error_msg=error_msg)
botocore.exceptions.SSOTokenLoadError: Error loading SSO Token: The SSO access token has either expired or is otherwise invalid.
Refreshing temporary credentials failed during mandatory refresh period.
Traceback (most recent call last):
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/botocore/credentials.py", line 322, in __getitem__
    with open(actual_key) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dwalkama/.aws/sso/cache/a7b00e6f99586adf164f6d395b1e7d4a2e3a8baf.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/botocore/utils.py", line 2773, in __call__
    token = self._cache[cache_key]
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/botocore/credentials.py", line 325, in __getitem__
    raise KeyError(cache_key)
KeyError: 'a7b00e6f99586adf164f6d395b1e7d4a2e3a8baf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/aiobotocore/credentials.py", line 321, in _protected_refresh
    metadata = await self._refresh_using()
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/aiobotocore/credentials.py", line 379, in fetch_credentials
    return await self._get_cached_credentials()
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/aiobotocore/credentials.py", line 389, in _get_cached_credentials
    response = await self._get_credentials()
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/aiobotocore/credentials.py", line 1013, in _get_credentials
    'accessToken': self._token_loader(self._start_url),
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/botocore/utils.py", line 2781, in __call__
    raise SSOTokenLoadError(error_msg=error_msg)
botocore.exceptions.SSOTokenLoadError: Error loading SSO Token: The SSO access token has either expired or is otherwise invalid.
```

I can subsequently run `aws s3 ls` and successfully see the buckets:

```
2023-03-03 14:57:04 *redacted*
2022-06-22 14:32:05 *redacted*
2021-02-19 11:17:02 *redacted*
2021-06-23 16:09:58 *redacted*
2022-11-17 10:52:47 *redacted*
2020-11-21 19:55:28 *redacted*
2021-07-16 09:56:13 *redacted*
2022-08-02 15:55:23 *redacted*
2023-02-16 05:18:29 *redacted*
2023-03-07 11:17:52 *redacted*
```

`dvc doctor` output:

```
DVC version: 2.47.2 (conda)
---------------------------
Platform: Python 3.10.9 on Linux-5.11.0-1022-aws-x86_64-with-glibc2.31
Subprojects:
        dvc_data = 0.42.3
        dvc_objects = 0.21.1
        dvc_render = 0.2.0
        dvc_task = 0.2.0
        scmrepo = 0.1.15
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.1.0, boto3 = 1.24.59)
Cache types: hardlink, symlink
Cache directory: nfs4 on *redacted ip*:/home
Caches: local, s3
Remotes: local, s3
Workspace directory: nfs4 on *redacted ip*:/home
Repo: dvc, git
```

**Comment by d-walkama** [comment] 2023-03-17 20:41
Any help with this would be greatly appreciated. Thanks in advance.

**Comment by shcheklein** [comment] 2023-03-17 22:52
@d-walkama right after it fails, if you run `aws s3 cp s3:\\<remote-path>\a7\b00e6f99586adf164f6d395b1e7d4a2e3a8baf .` does it work for you?

**Comment by d-walkama** [comment] 2023-03-23 20:28
@shcheklein 

dwalkama@refscluster:~$ aws s3 cp s3://<bucket>/<remote-path>/a7/b00e6f99586adf164f6d395b1e7d4a2e3a8baf .
fatal error: An error occurred (404) when calling the HeadObject operation: Key "<remote-path>/a7/b00e6f99586adf164f6d395b1e7d4a2e3a8baf" does not exist
dwalkama@refscluster:~$ aws s3 ls <bucket>/<remote-path>/a7
                           PRE a7/

**Comment by shcheklein** [comment] 2023-03-23 21:22
@d-walkama okay, sorry, I see. Can you try then to create an object with this name (`aws s3 cp <any-file> s3://<bucket>/<remote-path>/<some-file>`). Does it work for you? Do you see any files at all in the remote storage, btw?

**Comment by d-walkama** [comment] 2023-03-24 16:45
I'm able to see in the remote:

```
dwalkama@refscluster:~$ aws s3 ls <bucket>/<dvc-remote>/
                           PRE 00/
                           PRE 01/
                           PRE 02/
                           PRE 03/
                           PRE 04/
                           PRE 05/
                           PRE 06/
                           PRE 07/
                           PRE 08/
                           PRE 09/
                           PRE 0a/
                           PRE 0b/
                           PRE 0c/
```

I'm able to download:

```
dwalkama@refscluster:~$ aws s3 cp s3://<bucket>/<dvc-remote>/3a/1215b164b9b246e64c772f88b500b1 .
download: s3://<bucket>/<dvc-remote>/3a/1215b164b9b246e64c772f88b500b1 to ./1215b164b9b246e64c772f88b500b1
```
but DVC still fails when I try to use SSO:

```
Traceback (most recent call last):
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/botocore/credentials.py", line 322, in __getitem__
    with open(actual_key) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dwalkama/.aws/sso/cache/a7b00e6f99586adf164f6d395b1e7d4a2e3a8baf.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/botocore/utils.py", line 2773, in __call__
    token = self._cache[cache_key]
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/botocore/credentials.py", line 325, in __getitem__
    raise KeyError(cache_key)
KeyError: 'a7b00e6f99586adf164f6d395b1e7d4a2e3a8baf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/aiobotocore/credentials.py", line 321, in _protected_refresh
    metadata = await self._refresh_using()
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/aiobotocore/credentials.py", line 379, in fetch_credentials
    return await self._get_cached_credentials()
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/aiobotocore/credentials.py", line 389, in _get_cached_credentials
    response = await self._get_credentials()
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/aiobotocore/credentials.py", line 1013, in _get_credentials
    'accessToken': self._token_loader(self._start_url),
  File "/home/dwalkama/miniconda3/envs/*redacted*/lib/python3.10/site-packages/botocore/utils.py", line 2781, in __call__
    raise SSOTokenLoadError(error_msg=error_msg)
botocore.exceptions.SSOTokenLoadError: Error loading SSO Token: The SSO access token has either expired or is otherwise invalid.
```

**Comment by shcheklein** [comment] 2023-03-24 20:23
@d-walkama so, since you see some files in bucket, does it means that DVC wrote them somehow? Can is be the case that the operation takes longer then the lifetime of the token? If you refresh the token (auth again) and run `dvc push` again, does it fail right away?

**Comment by d-walkama** [comment] 2023-03-24 20:44
I'm able to use dvc to push/pull from S3 by setting AWS variables with session ID, etc. The error I'm seeing is when I try to use it with aws sso.

**Comment by shcheklein** [comment] 2023-03-25 01:21
@d-walkama I've tried to reproduce this. I'm not very familiar with AWS SSO, and was following [this](https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-token.html). `dvc push` worked fine for me, I set it apprx this way:

```
(.venv) √ Projects/get-parquet % aws configure sso
SSO start URL [None]: ********
SSO Region [None]: us-east-2
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.us-east-2.amazonaws.com/

Then enter the code:

********
The only AWS account available to you is: *******
Using the account ID *************
The only role available to you is: ************
Using the role name "*************"
CLI default client Region [us-east-2]:
CLI default output format [json]:
CLI profile name [test-sso]:

To use this profile, specify the profile name using --profile, as shown:

aws s3 ls --profile test-sso
```

And for DVC:

```
dvc remote add -d storage s3://bucket/test
dvc remote config storage profile test-sso
```

After this `dvc push` worked fine.

Could you try the latest DVC version. Could you check if something else is different on your end?

**Comment by shcheklein** [comment] 2023-03-31 20:16
@d-walkama I'm closing this since we can't reproduce this, but feel free to chime in and open it again.

**Closed by shcheklein** 2023-03-31 20:16 UTC
Labels: awaiting response
