### ISSUE TITLE
upload: MalformedACLError on Dell EMC S3

### ISSUE THREAD

**Issue by tpanza** [iterative/dvc-s3#38] opened 2023-04-15 22:54 UTC
# Bug Report

## Description

Trying to set up use of DVC with a remote S3. This S3 storage is not on AWS or any cloud provider, but is instead on-prem compatible S3 storage. The following (bizarre) error is displayed:

```console
Adding...
ERROR: unexpected error - [Errno 22] The XML you provided was not well-formed or did not validate against our published schema.: An error occurred (MalformedACLError) when calling the CreateMultipartUpload operation: The XML you provided was not well-formed or did not validate against our published schema.

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

### Reproduce

(`git add` and `git commit` commands omitted)

1. `export CURL_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt`
1. `export REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt`
1. `export AWS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt`
1. `export AWS_ACCESS_KEY_ID=mys3keyid`
1. `export AWS_SECRET_ACCESS_KEY=mys3secretaccesskey`
1. `python -m pip install dvc dvc-s3`
1. `dvc init`
1. `dvc remote add mys3remote s3://my-s3-bucket`
1. `dvc remote modify mys3remote endpointurl https://object1.cs.mycompany.com:9021`
1. `dvc config core.remote mys3remote`
1. create dataset.zip
1. `dvc add dataset.zip --to-remote -r mys3remote --verbose`

### Expected

Data file is added to remote S3 bucket

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.54.0 (pip)
-------------------------
Platform: Python 3.10.10 on Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-glibc2.17
Subprojects:
        dvc_data = 0.47.1
        dvc_objects = 0.21.1
        dvc_render = 0.3.1
        dvc_task = 0.2.0
        scmrepo = 1.0.1
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.4.0, boto3 = 1.26.76)
Cache types: hardlink, symlink
Cache directory: xfs on /dev/mapper/vg_localdata-lv_localdata
Caches: local
Remotes: s3
Workspace directory: xfs on /dev/mapper/vg_localdata-lv_localdata
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/f3b58e515e1cad4632ebc384f1b95d45
```

**Additional Information (if any):**

```
Adding...
2023-04-15 15:38:54,260 ERROR: unexpected error - [Errno 22] The XML you provided was not well-formed or did not validate against our published schema.: An error occurred (MalformedACLError) when calling the CreateMultipartUpload operation: The XML you provided was not well-formed or did not validate against our published schema.
Traceback (most recent call last):
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/s3fs/core.py", line 113, in _error_wrapper
    return await func(*args, **kwargs)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/aiobotocore/client.py", line 371, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (MalformedACLError) when calling the CreateMultipartUpload operation: The XML you provided was not well-formed or did not validate against our published schema.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc/commands/add.py", line 50, in run
    self.repo.add(
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc/utils/collections.py", line 160, in inner
    result = func(*ba.args, **ba.kwargs)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc/repo/__init__.py", line 65, in wrapper
    return f(repo, *args, **kwargs)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc/repo/scm_context.py", line 151, in run
    return method(repo, *args, **kw)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc/repo/add.py", line 187, in add
    stage.transfer(source, to_remote=to_remote, odb=odb, **kwargs)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc/stage/__init__.py", line 417, in transfer
    out.transfer(source, odb=odb, jobs=kwargs.get("jobs"))
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc/output.py", line 973, in transfer
    staging, self.meta, obj = build(
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc_data/hashfile/build.py", line 263, in build
    meta, obj = _build_file(
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc_data/hashfile/build.py", line 67, in _build_file
    return _upload_file(path, fs, odb, upload_odb)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc_data/hashfile/build.py", line 54, in _upload_file
    upload_odb.fs.put_file(stream, tmp_info, size=size, callback=cb)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 509, in put_file
    self.upload_fobj(stream, to_info, size=size)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 527, in upload_fobj
    shutil.copyfileobj(
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/shutil.py", line 198, in copyfileobj
    fdst_write(buf)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/fsspec/spec.py", line 1619, in write
    self.flush()
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/fsspec/spec.py", line 1655, in flush
    self._initiate_upload()
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/s3fs/core.py", line 2096, in _initiate_upload
    self.mpu = self._call_s3(
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/s3fs/core.py", line 2088, in _call_s3
    return self.fs.call_s3(method, self.s3_additional_kwargs, *kwarglist, **kwargs)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/fsspec/asyn.py", line 115, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/fsspec/asyn.py", line 100, in sync
    raise return_result
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/fsspec/asyn.py", line 55, in _runner
    result[0] = await coro
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/s3fs/core.py", line 348, in _call_s3
    return await _error_wrapper(
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/s3fs/core.py", line 140, in _error_wrapper
    raise err
OSError: [Errno 22] The XML you provided was not well-formed or did not validate against our published schema.

2023-04-15 15:38:54,290 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)
2023-04-15 15:38:54,290 DEBUG: Removing '/localdata/experiments/myname/my-gitlab-group-name/.fiDpjPyS3fVEf8RuYP4CoL.tmp'
2023-04-15 15:38:54,290 DEBUG: Removing '/localdata/experiments/myname/my-gitlab-group-name/.fiDpjPyS3fVEf8RuYP4CoL.tmp'
2023-04-15 15:38:54,290 DEBUG: Removing '/localdata/experiments/myname/my-gitlab-group-name/.fiDpjPyS3fVEf8RuYP4CoL.tmp'
2023-04-15 15:38:54,291 DEBUG: Removing '/localdata/experiments/myname/my-gitlab-group-name/my-gitlab-repo-name/.dvc/cache/.3TDpFh8cJmTHZN6AhAdXPP.tmp'
2023-04-15 15:40:32,026 DEBUG: Version info for developers:
DVC version: 2.54.0 (pip)
-------------------------
Platform: Python 3.10.10 on Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-glibc2.17
Subprojects:
        dvc_data = 0.47.1
        dvc_objects = 0.21.1
        dvc_render = 0.3.1
        dvc_task = 0.2.0
        scmrepo = 1.0.1
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.4.0, boto3 = 1.26.76)
Cache types: hardlink, symlink
Cache directory: xfs on /dev/mapper/vg_localdata-lv_localdata
Caches: local
Remotes: s3
Workspace directory: xfs on /dev/mapper/vg_localdata-lv_localdata
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/f3b58e515e1cad4632ebc384f1b95d45

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-04-15 15:40:32,028 DEBUG: Analytics is disabled.
```

**Comment by efiop** [comment] 2023-04-15 23:25
Seems similar https://stackoverflow.com/questions/45727244/malformedxml-the-xml-you-provided-was-not-well-formed-or-did-not-validate-again

Do you know what storage you are using by any chance? Minio? Something else?

Since this is a custom storage, probably something is missing in the response it is providing. You'll likely need to play around with it to see what's missing. Unfortunately you are on your own here, there is not much we can help with at this point 🙁 

Please let us know if you'll find something.

I'll close this for now, since it is not actionable for us.

**Comment by tpanza** [comment] 2023-04-15 23:46
@efiop It is Dell EMC S3 storage. I can tell you that it works out of the box just fine with other S3 clients, including MLflow, S3Browser, s3cmd, boto3. Just need to configure the client by setting the endpoint URL and the path to my CA bundle file (depending on the OS), which is what I did here.

**Comment by efiop** [comment] 2023-04-16 00:28
@tpanza Does uploading with `aws` CLI work?

**Comment by tpanza** [comment] 2023-04-16 00:29
@efiop I don't have the `aws` CLI installed. I just tried `s3fs` and it worked.

If I use `s3fs` directly, I can write to and read from this EMC S3-compatible storage just fine.

**Comment by efiop** [comment] 2023-04-16 00:32
@tpanza How do you configure `s3fs` in that case?

Could you try `dvc add` without `--to-remote` on some smaller file and then `dvc push -v`? Just to narrow down the scope.

**Comment by efiop** [comment] 2023-04-16 00:34
Looks related https://github.com/dask/dask/issues/8172

**Comment by efiop** [comment] 2023-04-16 00:36
@tpanza How big is that zip file, btw?

**Comment by tpanza** [comment] 2023-04-16 00:36
@efiop just set the `endpoint_url`. Rely on env vars for the rest: `AWS_CA_BUNDLE`, `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`

```python
>>> import s3fs
>>> s3 = s3fs.S3FileSystem(endpoint_url="https://object1.cs.mycompany.com:9021")
>>> s3.put('my-df.pkl', 'my-bucket/')
>>> import pandas as pd
>>> with s3.open('my-bucket/my-df.pkl', 'rb') as f:
...     df = pd.read_pickle(f)
>>> len(df)
5705
```

**Comment by efiop** [comment] 2023-04-16 00:38
@tpanza Is that the same file you are trying to `dvc add`? If not, could you try that same file? It might be related to multipart uploads which happen after a certain size threshhold.

**Comment by tpanza** [comment] 2023-04-16 00:39
> @tpanza How big is that zip file, btw?

It's actually a 31 MB pickled pandas DataFrame. I just called it a .zip for the purposes of a sanitized example.

**Comment by tpanza** [comment] 2023-04-16 00:42
> @tpanza Is that the same file you are trying to `dvc add`? If not, could you try that same file? It might be related to multipart uploads which happen after a certain size threshold.

@efiop yes, it's the same file I am trying to `dvc add`

**Comment by tpanza** [comment] 2023-04-16 00:52
> @tpanza How do you configure `s3fs` in that case? What methods do you use? Is it the same file you are uploading?
> 
> Could you try `dvc add` without `--to-remote` and then `dvc push -v`? Just to narrow down the scope.

@efiop please see output below

```
dvc add streamlit/my-dataframe.pkl
100% Adding...|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|1/1 [00:00, 15.53file/s]

To track the changes with git, run:

        git add streamlit/.gitignore streamlit/my-dataframe.pkl.dvc

To enable auto staging, run:

        dvc config core.autostage true
(streamlit) 17:43:03 [myusername@hostname my-gitlab-repo (my-git-branch)]$ dvc push -v
2023-04-15 17:43:27,762 DEBUG: v2.54.0 (pip), CPython 3.10.10 on Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-glibc2.17
2023-04-15 17:43:27,762 DEBUG: command: /app/local/mambaforge/envs/streamlit/bin/dvc push -v
2023-04-15 17:43:28,250 DEBUG: Preparing to transfer data from '/localdata/experiments/myname/my-gitlab-group/my-gitlab-repo/.dvc/cache' to 'my-s3-bucket'
2023-04-15 17:43:28,250 DEBUG: Preparing to collect status from 'my-s3-bucket'
2023-04-15 17:43:28,250 DEBUG: Collecting status from 'my-s3-bucket'
2023-04-15 17:43:28,251 DEBUG: Querying 1 oids via object_exists
2023-04-15 17:43:28,707 DEBUG: Preparing to collect status from '/localdata/experiments/myname/my-gitlab-group/my-gitlab-repo/.dvc/cache'
2023-04-15 17:43:28,707 DEBUG: Collecting status from '/localdata/experiments/myname/my-gitlab-group/my-gitlab-repo/.dvc/cache'
1 file pushed
2023-04-15 17:43:30,068 DEBUG: Analytics is disabled.
```

Reminder, in my `.dvc/config`, I have this S3 remote set as default.

And.... it worked??!?

Under the S3 bucket, there is now an object with this Key: `2a/9528151b6568c0f78d8e0a7b00797a` of size 31 MB

**Comment by efiop** [comment] 2023-04-16 00:54
Yep, looks like separating the steps worked. Not quite sure what's changed. Could you try deleting that file manually on the storage and trying your original command? Just want to see how reproducible it is.

**Comment by tpanza** [comment] 2023-04-16 01:14
> Yep, looks like separating the steps worked. Not quite sure what's changed. Could you try deleting that file manually on the storage and trying your original command? Just want to see how reproducible it is.

@efiop looks like same error

```
$ dvc add streamlit/my-dataframe.pkl --to-remote -r mys3remote --verbose
2023-04-15 18:10:52,698 DEBUG: v2.54.0 (pip), CPython 3.10.10 on Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-glibc2.17
2023-04-15 18:10:52,698 DEBUG: command: /app/local/mambaforge/envs/streamlit/bin/dvc add streamlit/my-dataframe.pkl --to-remote -r mys3remote --verbose
Adding...
2023-04-15 18:10:53,596 ERROR: unexpected error - [Errno 22] The XML you provided was not well-formed or did not validate against our published schema.: An error occurred (MalformedACLError) when calling the CreateMultipartUpload operation: The XML you provided was not well-formed or did not validate against our published schema.
Traceback (most recent call last):
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/s3fs/core.py", line 113, in _error_wrapper
    return await func(*args, **kwargs)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/aiobotocore/client.py", line 371, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (MalformedACLError) when calling the CreateMultipartUpload operation: The XML you provided was not well-formed or did not validate against our published schema.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc/commands/add.py", line 50, in run
    self.repo.add(
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc/utils/collections.py", line 160, in inner
    result = func(*ba.args, **ba.kwargs)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc/repo/__init__.py", line 65, in wrapper
    return f(repo, *args, **kwargs)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc/repo/scm_context.py", line 151, in run
    return method(repo, *args, **kw)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc/repo/add.py", line 187, in add
    stage.transfer(source, to_remote=to_remote, odb=odb, **kwargs)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc/stage/__init__.py", line 417, in transfer
    out.transfer(source, odb=odb, jobs=kwargs.get("jobs"))
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc/output.py", line 973, in transfer
    staging, self.meta, obj = build(
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc_data/hashfile/build.py", line 263, in build
    meta, obj = _build_file(
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc_data/hashfile/build.py", line 67, in _build_file
    return _upload_file(path, fs, odb, upload_odb)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc_data/hashfile/build.py", line 54, in _upload_file
    upload_odb.fs.put_file(stream, tmp_info, size=size, callback=cb)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 509, in put_file
    self.upload_fobj(stream, to_info, size=size)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 527, in upload_fobj
    shutil.copyfileobj(
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/shutil.py", line 198, in copyfileobj
    fdst_write(buf)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/fsspec/spec.py", line 1619, in write
    self.flush()
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/fsspec/spec.py", line 1655, in flush
    self._initiate_upload()
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/s3fs/core.py", line 2096, in _initiate_upload
    self.mpu = self._call_s3(
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/s3fs/core.py", line 2088, in _call_s3
    return self.fs.call_s3(method, self.s3_additional_kwargs, *kwarglist, **kwargs)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/fsspec/asyn.py", line 115, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/fsspec/asyn.py", line 100, in sync
    raise return_result
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/fsspec/asyn.py", line 55, in _runner
    result[0] = await coro
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/s3fs/core.py", line 348, in _call_s3
    return await _error_wrapper(
  File "/app/local/mambaforge/envs/streamlit/lib/python3.10/site-packages/s3fs/core.py", line 140, in _error_wrapper
    raise err
OSError: [Errno 22] The XML you provided was not well-formed or did not validate against our published schema.

2023-04-15 18:10:53,629 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)
2023-04-15 18:10:53,629 DEBUG: Removing '/localdata/experiments/myname/my-gitlab-group/.NSo7wVKGxJH4XYTLoZuqzQ.tmp'
2023-04-15 18:10:53,630 DEBUG: Removing '/localdata/experiments/myname/my-gitlab-group/.NSo7wVKGxJH4XYTLoZuqzQ.tmp'
2023-04-15 18:10:53,630 DEBUG: Removing '/localdata/experiments/myname/my-gitlab-group/.NSo7wVKGxJH4XYTLoZuqzQ.tmp'
2023-04-15 18:10:53,630 DEBUG: Removing '/localdata/experiments/myname/my-gitlab-group/my-gitlab-repo/.dvc/cache/.NmGVmgzRawUSFUcKZvkjdp.tmp'
2023-04-15 18:12:25,202 DEBUG: Version info for developers:
DVC version: 2.54.0 (pip)
-------------------------
Platform: Python 3.10.10 on Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-glibc2.17
Subprojects:
        dvc_data = 0.47.1
        dvc_objects = 0.21.1
        dvc_render = 0.3.1
        dvc_task = 0.2.0
        scmrepo = 1.0.1
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.4.0, boto3 = 1.26.76)
Cache types: hardlink, symlink
Cache directory: xfs on /dev/mapper/vg_localdata-lv_localdata
Caches: local
Remotes: s3
Workspace directory: xfs on /dev/mapper/vg_localdata-lv_localdata
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/f3b58e515e1cad4632ebc384f1b95d45

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-04-15 18:12:25,206 DEBUG: Analytics is disabled.
```

**Comment by efiop** [comment] 2023-04-16 01:16
@tpanza Could you try both a few times? Just want to know if this is reliably reproducible.

In the mean time thinking about the differences between two commands and if there is anything I can immediately put my finger on...

**Comment by tpanza** [comment] 2023-04-16 03:26
> @tpanza Could you try both a few times? Just want to know if this is reliably reproducible.
> 
> In the mean time thinking about the differences between two commands and if there is anything I can immediately put my finger on...

@efiop Able to reliably repeat about ~7 or so times. (to make testing faster, installed the aws cli) Examle test cycle:

```
$ dvc add streamlit/my-dataframe.pkl --to-remote
Adding...
ERROR: unexpected error - [Errno 22] The XML you provided was not well-formed or did not validate against our published schema.: An error occurred (MalformedACLError) when calling the CreateMultipartUpload operation: The XML you provided was not well-formed or did not validate against our published schema.

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
$
$ dvc add streamlit/my-dataframe.pkl
100% Adding...|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|1/1 [00:00, 14.75file/s]

To track the changes with git, run:

        git add streamlit/my-dataframe.pkl.dvc streamlit/.gitignore

To enable auto staging, run:

        dvc config core.autostage true
$ dvc push
1 file pushed
$ aws s3 --endpoint-url https://object1.cs.mycompany.com:9021 ls s3://my-s3-bucket/2a/9528151b6568c0f78d8e0a7b00797a
2023-04-15 20:19:43   32495308 9528151b6568c0f78d8e0a7b00797a
$ aws s3 --endpoint-url https://object1.cs.mycompany.com:9021 rm s3://my-s3-bucket/2a/9528151b6568c0f78d8e0a7b00797a
delete: s3://my-s3-bucket/2a/9528151b6568c0f78d8e0a7b00797a
$ dvc remove streamlit/my-dataframe.pkl.dvc
```

**Comment by efiop** [comment] 2023-04-16 19:34
@tpanza So only happens with `--to-remote` reliably and always works fine with all other approaches, right?

**Comment by tpanza** [comment] 2023-04-16 21:46
@efiop Yes. Well, I am too new to `dvc` to know what "all other" would consist of beyond `dvc add` (without remote), followed by `dvc push`

**Comment by efiop** [comment] 2023-04-16 22:23
So the difference is that with `--to-remote` we go through `HashStreamFile` workflow https://github.com/iterative/dvc-data/blob/c2a60666b968c82f443c171d27670233769f7fe4/src/dvc_data/hashfile/build.py#L46 which uses stream-based uploading https://github.com/iterative/dvc-objects/blob/04b12d050ea34c82e6b8ca4842cfa0c1f93b296e/src/dvc_objects/fs/base.py#L509 , while regular `push` is operating on whole files. Looks like we'll need to take a closer look there.

In your scenario, there is really a very minor benefit to using `--to-remote` with such small files. Adding everything you need locally and then doing `dvc push` once might even be faster. So I suppose the "workaround" of using `dvc push` should be adequate for you for now.

**Comment by edhenry** [comment] 2023-10-27 22:40
I'm hitting the same problem with `fsspec` and subsequently `s3fs`.

Versions:

```bash
fsspec                             2022.1.0      File-system specification
s3fs                               2022.1.0      Convenient Filesystem inte...
boto3                              1.20.24       The AWS SDK for Python
```

The error I'm seeing...

```bash
DatasetError: Failed while saving data to data set 
ParquetDataSet(filepath=SDS-IRL-Data/saraswati/data/dev/01_raw/KBA-GenAI/kba.par
quet, protocol={}, save_args={}).
[Errno 22] The XML you provided was not well-formed or did not validate against 
our published schema.
```

I've tried setting the `default_block_size` on the s3 client and it doesn't seem to help. This seemed to have worked in the past with `s3fs==2021.8.0`.

AWS CLI works. Uploading to other non-ECS arrays works, as well.

**Comment by efiop** [comment] 2023-10-27 23:14
@edhenry dell emc s3 too, right?

**Comment by edhenry** [comment] 2023-10-28 02:02
Yes! Dell ECS S3.

**Comment by edhenry** [comment] 2023-10-28 20:31
Update:

Updating s3fs seems to have fixed it.

```bash
(saraswati-Xk3mn2Bw-py3.10) (base) [root@node5 saraswati]# poetry show s3fs
 name         : s3fs                                    
 version      : 2023.10.0                               
 description  : Convenient Filesystem interface over S3 

dependencies
 - aiobotocore >=2.7.0,<2.8.0
 - aiohttp <4.0.0a0 || >4.0.0a0,<4.0.0a1 || >4.0.0a1
 - fsspec **2023.10.0**
```

**Comment by efiop** [comment] 2023-10-28 22:46
@edhenry Great! It should get picked up automatically from now on as latest. Thank you so much for trying it out!

@tpanza Could you give it a try as well?

Closing for now.

**Closed by efiop** 2023-10-28 22:46 UTC
